# ============================================================================
# RAILWAY.YML - Deployment Configuration
# ============================================================================

RAILWAY_YML_CONTENT = """
version: 0.1.0

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    
    start: python main.py
    
    environment:
      # API Keys (set in Railway dashboard)
      - ALPHA_VANTAGE_API_KEY
      - BINANCE_API_KEY
      - BINANCE_API_SECRET
      - COINGLASS_API_KEY
      - CRYPTOALERT_API_KEY
      - DEXCHECK_API_KEY
      - FRED_API_KEY
      - NEWSAPI_KEY
      - TELEGRAM_TOKEN
      - TELEGRAM_CHAT_ID
      - TELEGRAM_LOG_CHAT_ID
      - TWITTER_BEARER_TOKEN
      - BYBIT_API_KEY
      - BYBIT_API_SECRET
      - COINBASE_API_KEY
      - COINBASE_API_SECRET
      - CoinMarketCap_API_KEY
      - DATABASE_URL
      - PYTHON_VERSION=3.11
    
    healthCheck:
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=ai_trader
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=demir_ai
    
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
"""
