"""
🚀 DEMIR AI v5.2 - PostgreSQL Database Schema & Initialization
💾 100% Real Data Storage - Optimized for Performance
📊 Production-Grade Database Setup

Location: GitHub Root / database_schema_v5.2.sql (NEW FILE)
Size: ~500 lines
Author: AI Research Agent
Date: 2025-11-15
"""

-- ============================================================================
-- DATABASE CONNECTION SETUP (Run this first)
-- ============================================================================

-- Connect with: psql postgresql://user:pass@host:port/railway
-- Or use Railway CLI: railway postgresql connect

-- ============================================================================
-- SIGNAL/TRADES TABLE - STORES ALL REAL SIGNALS
-- ============================================================================

CREATE TABLE IF NOT EXISTS trades (
    id SERIAL PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    signal_type VARCHAR(10) NOT NULL CHECK (signal_type IN ('LONG', 'SHORT', 'NEUTRAL')),
    confidence FLOAT NOT NULL CHECK (confidence >= 0 AND confidence <= 100),
    entry_price NUMERIC(20,8) NOT NULL,
    take_profit_1 NUMERIC(20,8) NOT NULL,
    take_profit_2 NUMERIC(20,8) NOT NULL,
    take_profit_3 NUMERIC(20,8),
    stop_loss NUMERIC(20,8) NOT NULL,
    layer_scores JSONB,
    analysis_reason TEXT,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    status VARCHAR(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'CLOSED', 'CANCELLED')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for trades table
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol);
CREATE INDEX IF NOT EXISTS idx_trades_timestamp ON trades(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_trades_symbol_timestamp ON trades(symbol, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_trades_confidence ON trades(confidence DESC);
CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_created ON trades(created_at DESC);

-- Comment on table
COMMENT ON TABLE trades IS 'Real-time signals generated by DEMIR AI 62-layer ensemble';
COMMENT ON COLUMN trades.symbol IS 'Cryptocurrency symbol (e.g., BTCUSDT)';
COMMENT ON COLUMN trades.signal_type IS 'LONG (buy), SHORT (sell), or NEUTRAL (wait)';
COMMENT ON COLUMN trades.confidence IS 'Signal confidence 0-100%';
COMMENT ON COLUMN trades.layer_scores IS 'JSON with scores from 5 tiers: technical, ml, sentiment, onchain, risk';

-- ============================================================================
-- LAYER METRICS TABLE - DETAILED LAYER ANALYSIS
-- ============================================================================

CREATE TABLE IF NOT EXISTS layer_metrics (
    id SERIAL PRIMARY KEY,
    trade_id INTEGER NOT NULL REFERENCES trades(id) ON DELETE CASCADE,
    layer_name VARCHAR(100) NOT NULL,
    layer_tier VARCHAR(20) NOT NULL, -- technical, ml, sentiment, onchain, risk
    score FLOAT NOT NULL CHECK (score >= 0 AND score <= 1),
    analysis_data JSONB,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_layer_metrics_trade_id ON layer_metrics(trade_id);
CREATE INDEX IF NOT EXISTS idx_layer_metrics_layer_name ON layer_metrics(layer_name);
CREATE INDEX IF NOT EXISTS idx_layer_metrics_tier ON layer_metrics(layer_tier);

COMMENT ON TABLE layer_metrics IS '62-layer breakdown for each signal';

-- ============================================================================
-- PERFORMANCE TRACKING TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS performance_tracking (
    id SERIAL PRIMARY KEY,
    trade_id INTEGER NOT NULL REFERENCES trades(id) ON DELETE CASCADE,
    entry_price NUMERIC(20,8) NOT NULL,
    exit_price NUMERIC(20,8),
    profit_loss NUMERIC(20,8),
    profit_loss_percent FLOAT,
    status VARCHAR(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'TP1_HIT', 'TP2_HIT', 'TP3_HIT', 'SL_HIT', 'MANUAL_CLOSE')),
    entry_time TIMESTAMP WITH TIME ZONE NOT NULL,
    exit_time TIMESTAMP WITH TIME ZONE,
    duration_minutes INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_perf_trade_id ON performance_tracking(trade_id);
CREATE INDEX IF NOT EXISTS idx_perf_status ON performance_tracking(status);
CREATE INDEX IF NOT EXISTS idx_perf_entry_time ON performance_tracking(entry_time DESC);

-- ============================================================================
-- USER SETTINGS & PREFERENCES
-- ============================================================================

CREATE TABLE IF NOT EXISTS user_settings (
    id SERIAL PRIMARY KEY,
    setting_key VARCHAR(100) UNIQUE NOT NULL,
    setting_value TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert default settings
INSERT INTO user_settings (setting_key, setting_value, description) VALUES
    ('min_confidence_threshold', '70', 'Minimum signal confidence to trigger alerts'),
    ('min_signal_interval_seconds', '60', 'Minimum seconds between signals per symbol'),
    ('max_concurrent_positions', '5', 'Maximum number of open positions'),
    ('telegram_enabled', 'true', 'Enable Telegram notifications'),
    ('email_enabled', 'false', 'Enable email notifications'),
    ('dashboard_refresh_seconds', '5', 'Dashboard auto-refresh interval'),
    ('primary_symbols', 'BTCUSDT,ETHUSDT,LTCUSDT', 'Comma-separated list of primary coins'),
    ('price_verification_enabled', 'true', '100% Real Data: Verify entry price from exchange'),
    ('multi_exchange_enabled', 'true', 'Cross-validate prices from Binance, Bybit, Coinbase'),
    ('risk_management_enabled', 'true', 'Enable risk management checks'),
    ('system_mode', 'production', 'System mode: production or test (MUST be production)'),
    ('mock_data_check', 'strict', 'Mock data detection level: strict or lenient'),
    ('api_retry_attempts', '3', 'Number of API retry attempts'),
    ('api_timeout_seconds', '10', 'API timeout in seconds'),
    ('database_backup_daily', 'true', 'Enable daily database backups'),
    ('log_level', 'INFO', 'Logging level: DEBUG, INFO, WARNING, ERROR, CRITICAL')
ON CONFLICT (setting_key) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_user_settings_key ON user_settings(setting_key);

COMMENT ON TABLE user_settings IS 'System configuration and user preferences';

-- ============================================================================
-- API USAGE LOG - TRACK ALL API CALLS
-- ============================================================================

CREATE TABLE IF NOT EXISTS api_usage_log (
    id SERIAL PRIMARY KEY,
    api_name VARCHAR(50) NOT NULL, -- binance, bybit, coinbase, fred, etc
    endpoint VARCHAR(200) NOT NULL,
    status_code INTEGER,
    response_time_ms INTEGER,
    error_message TEXT,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_api_log_name ON api_usage_log(api_name);
CREATE INDEX IF NOT EXISTS idx_api_log_timestamp ON api_usage_log(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_api_log_status ON api_usage_log(status_code);

-- Cleanup old logs (keep only 30 days)
CREATE OR REPLACE FUNCTION cleanup_old_api_logs()
RETURNS void AS $$
BEGIN
    DELETE FROM api_usage_log WHERE timestamp < NOW() - INTERVAL '30 days';
    RAISE NOTICE 'Cleaned up API logs older than 30 days';
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- ALERT LOG - TRACK ALERTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS alert_log (
    id SERIAL PRIMARY KEY,
    alert_type VARCHAR(50) NOT NULL, -- signal, opportunity, risk, system
    alert_title VARCHAR(200) NOT NULL,
    alert_message TEXT,
    severity VARCHAR(20) DEFAULT 'INFO' CHECK (severity IN ('INFO', 'WARNING', 'ERROR', 'CRITICAL')),
    telegram_sent BOOLEAN DEFAULT FALSE,
    email_sent BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alert_log_type ON alert_log(alert_type);
CREATE INDEX IF NOT EXISTS idx_alert_log_severity ON alert_log(severity);
CREATE INDEX IF NOT EXISTS idx_alert_log_timestamp ON alert_log(timestamp DESC);

-- ============================================================================
-- SYSTEM STATUS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS system_status (
    id SERIAL PRIMARY KEY,
    component_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ONLINE', 'OFFLINE', 'DEGRADED', 'ERROR')),
    last_heartbeat TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    error_message TEXT,
    metrics JSONB,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_system_status_component ON system_status(component_name);
CREATE INDEX IF NOT EXISTS idx_system_status_status ON system_status(status);

-- Insert initial system components
INSERT INTO system_status (component_name, status) VALUES
    ('database', 'ONLINE'),
    ('api_binance', 'ONLINE'),
    ('api_bybit', 'ONLINE'),
    ('api_coinbase', 'ONLINE'),
    ('telegram_bot', 'ONLINE'),
    ('signal_generator', 'ONLINE'),
    ('ai_brain', 'ONLINE'),
    ('websocket_stream', 'ONLINE')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Function to get recent signals
CREATE OR REPLACE FUNCTION get_recent_signals(
    p_symbol VARCHAR DEFAULT NULL,
    p_limit INTEGER DEFAULT 50,
    p_hours_back INTEGER DEFAULT 24
)
RETURNS TABLE (
    signal_id INTEGER,
    symbol VARCHAR,
    signal_type VARCHAR,
    confidence FLOAT,
    entry_price NUMERIC,
    tp1 NUMERIC,
    tp2 NUMERIC,
    tp3 NUMERIC,
    sl NUMERIC,
    timestamp TIMESTAMP WITH TIME ZONE
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        t.id,
        t.symbol,
        t.signal_type,
        t.confidence,
        t.entry_price,
        t.take_profit_1,
        t.take_profit_2,
        t.take_profit_3,
        t.stop_loss,
        t.timestamp
    FROM trades t
    WHERE (p_symbol IS NULL OR t.symbol = p_symbol)
        AND t.timestamp > NOW() - (p_hours_back || ' hours')::INTERVAL
    ORDER BY t.timestamp DESC
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql;

-- Function to calculate win rate
CREATE OR REPLACE FUNCTION get_win_rate(
    p_days INTEGER DEFAULT 7
)
RETURNS TABLE (
    total_trades INTEGER,
    winning_trades INTEGER,
    losing_trades INTEGER,
    win_rate_percent FLOAT
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        COUNT(*)::INTEGER as total,
        SUM(CASE WHEN profit_loss > 0 THEN 1 ELSE 0 END)::INTEGER as wins,
        SUM(CASE WHEN profit_loss < 0 THEN 1 ELSE 0 END)::INTEGER as losses,
        (SUM(CASE WHEN profit_loss > 0 THEN 1 ELSE 0 END)::FLOAT / NULLIF(COUNT(*), 0) * 100)::FLOAT as rate
    FROM performance_tracking
    WHERE entry_time > NOW() - (p_days || ' days')::INTERVAL;
END;
$$ LANGUAGE plpgsql;

-- Function to log API usage
CREATE OR REPLACE FUNCTION log_api_usage(
    p_api_name VARCHAR,
    p_endpoint VARCHAR,
    p_status_code INTEGER,
    p_response_time_ms INTEGER,
    p_error_message VARCHAR DEFAULT NULL
)
RETURNS void AS $$
BEGIN
    INSERT INTO api_usage_log (api_name, endpoint, status_code, response_time_ms, error_message)
    VALUES (p_api_name, p_endpoint, p_status_code, p_response_time_ms, p_error_message);
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- MATERIALIZED VIEWS FOR PERFORMANCE
-- ============================================================================

CREATE MATERIALIZED VIEW IF NOT EXISTS signals_24h_summary AS
SELECT
    symbol,
    COUNT(*) as signal_count,
    ROUND(AVG(confidence), 2) as avg_confidence,
    MAX(confidence) as max_confidence,
    MIN(confidence) as min_confidence,
    SUM(CASE WHEN signal_type = 'LONG' THEN 1 ELSE 0 END) as long_count,
    SUM(CASE WHEN signal_type = 'SHORT' THEN 1 ELSE 0 END) as short_count,
    SUM(CASE WHEN signal_type = 'NEUTRAL' THEN 1 ELSE 0 END) as neutral_count
FROM trades
WHERE timestamp > NOW() - INTERVAL '24 hours'
GROUP BY symbol;

CREATE INDEX IF NOT EXISTS idx_signals_24h_symbol ON signals_24h_summary(symbol);

-- ============================================================================
-- GRANT PERMISSIONS
-- ============================================================================

-- Grant all permissions to railway user
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;
GRANT USAGE ON SCHEMA public TO postgres;

-- ============================================================================
-- VERIFICATION QUERIES (Run these to verify setup)
-- ============================================================================

-- Verify tables created
SELECT table_name FROM information_schema.tables WHERE table_schema='public';

-- Verify indexes created
SELECT indexname FROM pg_indexes WHERE schemaname='public';

-- Check user settings
SELECT setting_key, setting_value FROM user_settings LIMIT 5;

-- Check initial system status
SELECT component_name, status FROM system_status;

-- ============================================================================
-- DATABASE BACKUP RECOMMENDATION
-- ============================================================================

-- Automated daily backup recommendation (add to cron):
-- 0 2 * * * pg_dump -h $HOST -U $USER $DB > backup_$(date +\%Y\%m\%d).sql

-- Railway automatic backups: Enabled by default
-- Point-in-time recovery: Available for last 7 days

